## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt: # apt-get for linux
    packages:
    - gfortran

coveralls: true
